# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular BUild And Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Node Js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm run test:ci
      - name: Build
        run: npm run build
#      - name: Build Production
 #       run: npm run build:prod
